on: [push, pull_request]

name: R-CMD

jobs:
  R-CMD:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (TF ${{ matrix.config.tf }}) (KERAS-TUNER ${{ matrix.config.keras-tuner }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, tf: '2.0.0', keras-tuner: '1.0.1'}
        - { os: macOS-latest, tf: '2.0.0', keras-tuner: '1.0.1'}
        - { os: ubuntu-16.04,  cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", tf: '2.0.0', keras-tuner: '1.0.1'}
        - { os: windows-latest, tf: '2.1.0', keras-tuner: '1.0.1'}
        - { os: macOS-latest, tf: '2.1.0', keras-tuner: '1.0.1'}
        - { os: ubuntu-16.04,  cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", tf: '2.1.0', keras-tuner: '1.0.1'}
        - { os: windows-latest, tf: '2.2.0', keras-tuner: '1.0.1'}
        - { os: macOS-latest, tf: '2.2.0', keras-tuner: '1.0.1'}
        - { os: ubuntu-16.04,  cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", tf: '2.2.0', keras-tuner: '1.0.1'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      TF_VERSION: ${{ matrix.config.tf }}
      KERAS_TUNER_VERSION: ${{ matrix.config.keras-tuner }}
      PIP_NO_WARN_SCRIPT_LOCATION: false
      RETICULATE_AUTOCONFIGURE: 'FALSE'
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install build-essential checkinstall libx11-dev libxext-dev zlib1g-dev libpng12-dev libjpeg-dev libfreetype6-dev libxml2-dev
          cd /opt
          sudo wget http://www.imagemagick.org/download/ImageMagick.tar.gz
          sudo tar xvzf ImageMagick.tar.gz
          cd ImageMagick-7.0.8-2
          sudo touch configure
          sudo ./configure
          sudo make
          sudo make install
          sudo ldconfig /usr/local/lib
          sudo make check
          convert --version
          
      - name: Install MacOS/Windows
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          Rscript -e "remotes::install_cran('rcmdcheck')"

      - name: Install Python
        run: |
          Rscript -e "remotes::install_github('rstudio/reticulate')"
          Rscript -e "try(reticulate::install_miniconda())"
          Rscript -e "reticulate::conda_create('r-reticulate', packages = 'python==3.6.10')"
      - name: Install TensorFlow
        run: |
          Rscript -e "remotes::install_local()"
          Rscript -e "tensorflow::install_tensorflow(version = Sys.getenv('TF_VERSION'))"
          Rscript -e "reticulate::py_install(c('setuptools', 'wheel', 'requests'), pip = TRUE)"
          Rscript -e "kerastuneR::install_kerastuner()"
      - name: Check
        continue-on-error: ${{ matrix.config.allow_failure }}
        
        

        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"
